spring:
  application:
    name: fitjourneyai

  datasource:
    url: jdbc:postgresql://localhost:5432/fitjourneyai
    username: fitjourney
    password: fitjourney
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
openai:
  api:
    key: ${OPENAI_API_KEY}
